# Generated by Django 4.2.5 on 2023-09-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Campaign",
            new_name="Campaigns",
        ),
    ]
