# Generated by Django 4.2.5 on 2023-09-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_rename_campaign_campaigns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaigns",
            old_name="active",
            new_name="is_active",
        ),
    ]
